### ISSUE TITLE
Change default shell to bash

### ISSUE THREAD

**Issue by riker09** [w9jds/firebase-action#103]
My GitHub workflows broke over the weekend. A quick investigation showed that you updated your base image recently.

This is my GitHub action;

```yaml
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:myapp --message \"${COMMIT_MESSAGE:0:200}\"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ env.PROJECT_ID }}
```

and it results in this error: `sh: 1: Bad substitution`.

Yes, I know, relying on `@master` is a terrible idea and in fact the reason why *my* workflows went south. However, I would greatly appreciate it if you could change the default shell of the buster image back to `bash` so I could use `\"${COMMIT_MESSAGE:0:200}\".`
