### ISSUE TITLE
Failed to authenticate

### ISSUE THREAD

**Issue by muazamkamal** [w9jds/firebase-action#107]
I am trying to authenticate using GCP_SA_KEY and after double-checking with #39, making sure the JSON file is encoded as base64, it is still failing. Am I doing something wrong or deploying functions is not working?

![image](https://user-images.githubusercontent.com/5335874/129339011-160db540-31e5-45ac-ae32-ee1257025ec2.png)

This is the step I use
```
- name: Deploying Firebase Functions
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
```
