### ISSUE TITLE
Deploy to preview channels on:pull_request

### ISSUE THREAD

**Issue by stevecode21** [w9jds/firebase-action#109]
Is it possible to create a .yml file to deploy to firebase preview channels? If so, how can I accomplish it?

**Comment by abraham** [comment]
You can use something like this:

```yaml
      - uses: w9jds/firebase-action@v2.0.0
        with:
          args: hosting:channel:deploy pr${{github.event.pull_request.number}}
```

A perk of https://github.com/marketplace/actions/deploy-to-firebase-hosting though is it'll comment on the PR with a link to the preview.
