### ISSUE TITLE
Deploy target xxx not configured for project

### ISSUE THREAD

**Issue by noelmace** [w9jds/firebase-action#11]
I need to deploy each branch of my project (except `master`, which has its own workflow for GitHub pages) to a different firebase hosting site target. In order to do that, I just set the right target in each branch, and defined this workflow:

```
name: Branches Firebase Deploy
   
on:
  push:
    branches:
      - parisweb-2019
      - devfestnantes-2019

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
```

Yet, I get the following error:

```
=== Deploying to 'wof-show'...

i  deploying hosting

Error: Deploy target devfestnantes-2019 not configured for project wof-show. Configure with:

  firebase target:apply hosting devfestnantes-2019 <resources...>
##[error]Docker run failed with exit code 1
```

even if the target is indeed configured in:

https://github.com/noelmace/slides-wof-conf/blob/b5a54c26d55bac92237a5ef24d1e9b2fed8ed11f/.firebaserc

and, of course, exist on Firebase.

```
IT WORKS
¯\_(ツ)_/¯
on my machine
```

Here is my project: https://github.com/noelmace/slides-wof-conf
