### ISSUE TITLE
Error: Deploy target prod not configured for project project-name.

### ISSUE THREAD

**Issue by Paul-creator** [w9jds/firebase-action#111]
```
Error: Deploy target prod not configured for project project-name. Configure with:
  firebase target:apply hosting prod <resources...>
```
this is the part in the deploy.yml 
```
name: Deploy to Firebase Development
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --message \"${{ github.event.head_commit.message }}\"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: project-name
```
and this is the firebaserc
```
{
  "projects": {
    "prod": "project-name",
    "default": "project-name"
  },
  "targets": {
    "project-name": {
      "hosting": {
        "prod": [
          "project-name"
        ]
      }
    }
  }
}
```
