### ISSUE TITLE
Support For Workload Identity Federation/Impersonated Accounts

### ISSUE THREAD

**Issue by enchorb** [w9jds/firebase-action#123]
Any plans to allow authenticating via impersonation & WLIF? I've provided an example below of a potential flow.

```
- id: auth
   name: Authenticate to Google Cloud
   uses: google-github-actions/auth@v0.4.1
   with:
       token_format: access_token
       access_token_lifetime: 1200s
       create_credentials_file: true
       workload_identity_provider: ...
       service_account: ${{ secrets.WLIF_SERVICE_ACCOUNT }}

  - name: Firebase
        uses: w9jds/firebase-action@master
        with:
           args: deploy --only functions
        env:
           GCP_SA_KEY: ${{ steps.auth.output.credentials_file_path }}
           --- or ---
           GCP_ACCESS_TOKEN: ${{ steps.auth.output.access_token }}
```
