### ISSUE TITLE
functions: got "Quota Exceeded" error while trying to update projects/loopay-test/locations/us-central1/functions/timestamper-createdAt_Transactions. Waiting to retry

### ISSUE THREAD

**Issue by ortegoncarlos** [w9jds/firebase-action#125]

**Comment by ortegoncarlos** [comment]
As a workaround Im doing it in separate steps per group like the following
```

       - name: run deploy functions bgchecker
        uses: w9jds/firebase-action@master
        with:
            args: deploy --only functions:bgchecker --project=staging --force
        env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_PROD }}

      - name: run deploy functions mailer
        uses: w9jds/firebase-action@master
        with:
            args: deploy --only functions:mailer --project=staging --force
        env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_PROD }}
      - name: run deploy functions:sync
        uses: w9jds/firebase-action@master
        with:
            args: deploy --only functions:sync --project=staging --force
        env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_PROD }}
```
