### ISSUE TITLE
Unable to use SHA ref in workflow

### ISSUE THREAD

**Issue by riker09** [w9jds/firebase-action#131]
It is not possible to use this action in a workflow when using a specific version. Please also see my post in the GitHub Community Forum https://github.community/t/using-a-sha-for-remote-actions-not-working-as-expected/251451

In short:

```yaml
    name: 'GitHub Action for Firebase'
    author: 'Jeremy Shore'
    description: 'Wraps the firebase-tools CLI to enable common commands.'
    branding:
      icon: 'package'
      color: 'gray-dark'
    runs:
      using: 'docker'
      image: 'docker://w9jds/firebase-action:latest'
```

The Docker image is always using `:latest`. I don't know if it is possible to use a tag or SHA here provided by the remote (aka. "my") workflow. But currently this action contradicts the security best practices from GitHub itself: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
