### ISSUE TITLE
Actions fails without proper message

### ISSUE THREAD

**Issue by Safnaj** [w9jds/firebase-action#137]
I am currently deploying my mono repo react frontend to Firebase using the Actions. Getting below error message.

![Screenshot 2022-06-05 at 5 41 30 PM](https://user-images.githubusercontent.com/37530024/172049808-eb65d962-6b41-48d6-8c3e-0773344c75c6.png)

My Actions

```
name: Firebase Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build & deploy:
    defaults:
      run:
        working-directory: my-blog
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
```
