### ISSUE TITLE
how do i get the outputs ? 

### ISSUE THREAD

**Issue by johnico** [w9jds/firebase-action#145]
my workflow 

```
  - uses: w9jds/firebase-action@master
      id: firebase-deploy-hosting
      with:
        args: deploy --only hosting --force
      env:
        PROJECT_ID: ${{ inputs.project-id}}
        FIREBASE_TOKEN: ${{ inputs.firebase-token}} 
  - name: test
      shell: bash
      run: |
        echo $TEST
      env:
          TEST: ${{ toJson(steps.firebase-deploy-hosting) }}
```

and the outputs is empty

```
{ "outputs": {}, "outcome": "success", "conclusion": "success" }

```
