### ISSUE TITLE
Error deploy storage targets: rules

### ISSUE THREAD

**Issue by chikugoy** [w9jds/firebase-action#148]
Hi! Our CI/CD broke, which uses this package. We get this error:

```
=== Deploying to 'xxxx-staging'...

i  deploying database, storage, firestore
i  database: checking rules syntax...
✔  database: rules syntax for database xxxx-staging-default-rtdb is valid

Error: Could not find rules for the following storage targets: rules
```

deploy yml
```
jobs:
  deploy_rules:
    name: Deploy Firestore Rules
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only firestore:rules,storage:rules,database
```
