### ISSUE TITLE
Problem deploying multi sites on firebase hosting

### ISSUE THREAD

**Issue by jesusplayer** [w9jds/firebase-action#15]
Hello thank you for this awsome tool, please i have an issue when deploying my project
the project have multiple firebase sites. 
when I build project in stagging or prod mode, I have 2 folders :  **dist/stag** and **dist/prod**
So when I use firebase-action in stag mode, it fails on deployment, saying that the folder **dist/stag** is not found. But this works well when i deploy with my OS

this is the workflow

```  yml

name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Installation des dépendances et packaging (build) du projet
      run: |
        npm i
        npm ci
    - name: Packaging (build) du projet
      run: npm run build
    - name: Archivage des Artifacts
      uses: actions/upload-artifact@master
      with:
        name: dist_stag
        path: dist/stag
      env:
        CI: true
  deploy:
    name: Deploiement sur firebase
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Téléchargement des Artifacts
        uses: actions/download-artifact@master
        with:
          name: dist_stag
      - name: Deploiement sur firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:stag
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: semges-b24ca
``` 

This is the github output:

![image](https://user-images.githubusercontent.com/11212084/68937650-131aba00-079d-11ea-957c-4df1f40bfb90.png)

Thanks in advance for your help.
