### ISSUE TITLE
Run failed for appdistribution:distribute

### ISSUE THREAD

**Issue by burhankhanzada** [w9jds/firebase-action#154]
i want to to use firebase app distribution but i have tired all ways i can think off but run failed without any error to identify issue

# Step

```yml
      - name: Upload binaries to firebase app distribution
        uses: w9jds/firebase-action@master
        with:
          args: appdistribution:distribute --app ${{ secrets.FIREBASE_APP_ID }}$ --groups all build/**/outputs/flutter-apk/*.apk
        env:
          GCP_SA_KEY: ${{ secrets.FIREBSAE_SERVICE_ACCOUNT }}
```

# Output

```sh
Run w9jds/firebase-action@master
  with:
    args: appdistribution:distribute --app ***$ --groups all build/**/outputs/flutter-apk/*.apk
  env:
    FLUTTER_ROOT: /opt/hostedtoolcache/flutter/stable-[3](https://github.com/burhankhanzada/temp3/actions/runs/3194807853/jobs/5214763975#step:9:3).3.[4](https://github.com/burhankhanzada/temp3/actions/runs/3194807853/jobs/5214763975#step:9:4)-x64
    PUB_CACHE: /opt/hostedtoolcache/flutter/stable-3.3.4-x64/.pub-cache
    GCP_SA_KEY: ***
/usr/bin/docker run --name w9jdsfirebaseactionv1190_f[5](https://github.com/burhankhanzada/temp3/actions/runs/3194807853/jobs/5214763975#step:9:5)[6](https://github.com/burhankhanzada/temp3/actions/runs/3194807853/jobs/5214763975#step:9:6)64d --label 5364e3 --workdir /github/workspace --rm -e "FLUTTER_ROOT" -e "PUB_CACHE" -e "GCP_SA_KEY" -e "INPUT_ARGS" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/temp3/temp3":"/github/workspace" w[9](https://github.com/burhankhanzada/temp3/actions/runs/3194807853/jobs/5214763975#step:9:10)jds/firebase-action:v11.9.0 appdistribution:distribute --app ***$ --groups all build/**/outputs/flutter-apk/*.apk
Storing GCP_SA_KEY in /opt/gcp_key.json
Exporting GOOGLE_APPLICATION_CREDENTIALS=/opt/gcp_key.json
```
