### ISSUE TITLE
How to deploy function to different project

### ISSUE THREAD

**Issue by piggy0713** [w9jds/firebase-action#157]
I am trying to use this action to deploy the function to a separate project with a separate GCP account for development and staging. Development workflow works fine, but then when I push to staging.  I keep getting the error: Failed to authenticate, have you run firebase login?

here is my yml file
```
name: Deploy Function on staging Merge
on:
  push:
    branches:
      - staging

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - name: Install Dependencies
        run: |
          cd functions
          npm install
      - name: Deploy to Firebase
        uses: docker://w9jds/firebase-action:master
        with:
          args: deploy --only functions
        env:
          GCP_SA_KEY: gcp_key
          PROJECT_ID: project_id
```
