### ISSUE TITLE
Error: Cloud Functions deployment requires the Cloud Build API to be enabled.

### ISSUE THREAD

**Issue by anthonyjdella** [w9jds/firebase-action#158]
My action:

```
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        FIREBASE_PROJECT: {name-of-my-project}
        NODE_ENV: production
```

Error:

```
=== Deploying to project'...

i  deploying database, functions, hosting
Running command: echo no predeploy
no predeploy
✔  functions: Finished running predeploy script.
i  database: checking rules syntax...
✔  database: rules syntax for database project-rtdb is valid
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
i  artifactregistry: ensuring required API artifactregistry.googleapis.com is enabled...

**Error: Cloud Functions deployment requires the Cloud Build API to be enabled. The current credentials do not have permission to enable APIs for project my-project.**

Please ask a project owner to visit the following URL to enable Cloud Build:

https://console.cloud.google.com/apis/library/cloudbuild.googleapis.com?project=my-project

For additional information about this requirement, see Firebase FAQs:
https://firebase.google.com/support/faq#functions-runtime
```

Not really sure if this is an issue related to this Action or GCP. **But my Cloud Build API is already enabled!** Error says it's not enabled, but it is.
