### ISSUE TITLE
Not in a firebase app directory on a project generated from firebase init

### ISSUE THREAD

**Issue by iiian** [w9jds/firebase-action#18]
```
Run w9jds/firebase-action@v1.1.0
/usr/bin/docker run --name af96b4b1bb0a9277d1436495a5cb747b36f25f_d21aa3 --label af96b4 --workdir /github/workspace --rm -e FIREBASE_TOKEN -e INPUT_ARGS -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/getting-things-done/getting-things-done":"/github/workspace" af96b4:b1bb0a9277d1436495a5cb747b36f25f deploy

Error: Not in a Firebase app directory (could not locate firebase.json)
##[error]Docker run failed with exit code 1
```

1. I have exported my firebase token to a secret
2. .firebaserc lives at the root level of my repository
3. firebase.json lives at the root level of my repository

Not sure what's failing here.

**Comment by imr22** [comment]
> ```
> Run w9jds/firebase-action@v1.1.0
> /usr/bin/docker run --name af96b4b1bb0a9277d1436495a5cb747b36f25f_d21aa3 --label af96b4 --workdir /github/workspace --rm -e FIREBASE_TOKEN -e INPUT_ARGS -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/getting-things-done/getting-things-done":"/github/workspace" af96b4:b1bb0a9277d1436495a5cb747b36f25f deploy
> 
> Error: Not in a Firebase app directory (could not locate firebase.json)
> ##[error]Docker run failed with exit code 1
> ```
> 
> 1. I have exported my firebase token to a secret
> 2. .firebaserc lives at the root level of my repository
> 3. firebase.json lives at the root level of my repository
> 
> Not sure what's failing here.

**Comment by iiian** [comment]
Here is my `main.yml`:

`name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v1.1.0
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}`

**Comment by web-study-2019** [comment]
I have the same problem

<img width="1310" alt="Снимок экрана 2019-12-12 в 23 03 18" src="https://user-images.githubusercontent.com/37731120/70744984-ef16ae00-1d33-11ea-8b46-ee07308931da.png">

**Comment by w9jds** [comment]
Your issue is that you haven't copied over your code to this container at all. You don't build your project either. You are ultimately trying to deploy an empty container.

**Comment by dsp9107** [comment]
Same error with this workflow 👇

```yaml
name: deploy-to-Firebase-Hosting

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build-react-app
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
        
      - name: Install Dependencies
        run: npm install
        
      - name: Build the React app
        run: npm run build
      
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
        
  deploy:
    name: deploy-to-firebase
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
```

Fails like this 👇

✔️ **Set up job3s**
✔️ **Build w9jds/firebase-action@master57s**
✔️ **Download Artifact**
❌ **Deploy to Firebase**
```
/usr/bin/docker run --name e33463a79eed6eb45443d83f8e35e6107bd6a_d407d9 --label 9e3346 --workdir /github/workspace --rm -e FIREBASE_TOKEN -e INPUT_ARGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/pn-front/pn-front":"/github/workspace" 9e3346:3a79eed6eb45443d83f8e35e6107bd6a deploy --only hosting

Error: Not in a Firebase app directory (could not locate firebase.json)
```

There seems to be nothing wrong with the **firebase project** as the deploy command works fine locally via terminal as well as codespaces. The issue seems to be with the workflow.

What am I doing wrong?
