### ISSUE TITLE
Impossible to deploy with spaces in a CONFIG_VALUES value

### ISSUE THREAD

**Issue by damargulis** [w9jds/firebase-action#182]
Hi,

I am attempting to use this tool to do our firebase deploys, including setting the config values, but I can't figure out how to get this to work when one of the values has a space in it.

For example, using the step like:
```

- name: Deploy to Firebase
  id: firebase-deploy
  uses: w9jds/firebase-action@master
  with:
    args: deploy --only functions
  env:
    GCP_SA_KEY: ${{ secrets.sa-key }}
    CONFIG_VALUES:
      test.key="This is the value"
```

errors with "Error: Invalid argument is, must be in key=val format"
Ideally, I would like to have the value stored in a github secret, and passed through to this action. 
Is this possible to do?
