### ISSUE TITLE
Deploy step failing for codebase in subdirectory

### ISSUE THREAD

**Issue by nomeacuerdo** [w9jds/firebase-action#20]
Hi! I'm having some trouble getting to run this action running with the deployable code stored in the `./client` subfolder. It's always failing in the _Deploy to Firebase_ step.

My **main.yml** file looks as follows:

```
name: Build and Deploy Gatsby Client
on:
  push:
    branches:
      - master
jobs:
  build-client:
    name: Build Client
    runs-on: ubuntu-latest
    steps:
      - name: Yarn Installation
        run: |
          mkdir ~/.npm-global
          npm config set prefix '~/.npm-global'
          export PATH=~/.npm-global/bin:$PATH
          source ~/.profile
          npm install -g yarn
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          cd client
          yarn install
      - name: Build
        run: |
          cd client
          yarn build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: built-client
          path: client/public
  deploy-client:
    name: Deploy Client
    needs: build-client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: built-client
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.CLIENT_FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.CLIENT_FIREBASE_ID }}
          PROJECT_PATH: ./client
```

My **./client/firebase.json**:
```
{
  "hosting": {
    "public": "public",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  }
}
```

And the error that I'm getting is:
`Error: Specified public directory 'public' does not exist, can't deploy hosting to site ***`

Thank you if you can help me to figure out what's not properly configured.

**Comment by Niweera** [comment]
```yaml
name: Build and Deploy Gatsby Client
on:
  push:
    branches:
      - master
jobs:
  build-client:
    name: Build Client
    runs-on: ubuntu-latest
    steps:
      - name: Yarn Installation
        run: |
          mkdir ~/.npm-global
          npm config set prefix '~/.npm-global'
          export PATH=~/.npm-global/bin:$PATH
          source ~/.profile
          npm install -g yarn
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          cd client
          yarn install
      - name: Build
        run: |
          cd client
          yarn build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: built-client
          path: ./client/public
  deploy-client:
    name: Deploy Client
    needs: build-client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: built-client
          path: ./client/public
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.CLIENT_FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.CLIENT_FIREBASE_ID }}
          PROJECT_PATH: ./client
```

Try this...
