### ISSUE TITLE
Error: In non-interactive mode but have no value for the following environment variables: PROJECT_ID

### ISSUE THREAD

**Issue by csacsi** [w9jds/firebase-action#208]
Hi there, 

I added the project ID as an env value, but it still doesn't like it. Is there a bug in the script or I'm missing something?

My GithubAction looks like this:
```
- name: Deploy to firebase
        uses: w9jds/firebase-action@v12.8.0
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: Firebase/functions
          PROJECT_ID: "{...PROJECT_ID...}"
```
