### ISSUE TITLE
What is the point?

### ISSUE THREAD

**Issue by 0x80** [w9jds/firebase-action#221]
I am having a hard time seeing any benefits that this action brings.

In the past, I've defined `firebase-tools` as a dev dependency, and installed it in github actions with the other dependencies. Then you can execute any command as usual, or via a package.json script entry like `- run: pnpm run deploy:prd`.

What does this action allow me to do easily that would be problematic with my current approach?

**Comment by y-takebe** [comment]
Lately I was thinking the same thing, because every time I update fairebase-tools, this actions breaks and stops continuous deployment.

https://github.com/w9jds/firebase-action/blob/master/entrypoint.sh

I think the point of this actions is to absorb differences in parameter settings, but I would like to hear the Contributer's opinion.

So I have stopped using this actions, while thanking them for their contribution so far. My new code is as follows It works comfortably.

```
    - uses: w9jds/setup-firebase@main
      with:
        tools-version: 13.4.0
        gcp_sa_key: ${{ secrets.GCP_SA_KEY }}

    - name: Deploy to Firebase
      run: |
        firebase deploy --force --only functions:my-function,hosting:my-hosting-site --project my-project-id
        rm /opt/gcp_key.json
      working-directory: packages/myapp/
```

Points:
- [w9jds/setup-firebase](https://github.com/w9jds/setup-firebase) has created `/opt/gcp_key.json` and [set the path to the environment variable](https://github.com/w9jds/setup-firebase/blob/main/src/auth.ts) `GOOGLE_APPLICATION_CREDENTIALS` and use it.
- `rm /opt/gcp_key.json` for unexpected security breaches.

**Comment by BenJackGill** [comment]
Incase anyone comes along later, I used the `google-github-actions/auth@v2` to login to my Google account before running the npm script.

This is a short version of how it looks in my Github actions:

```
  firebase-functions:
    name: Firebase Functions
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ var.PROJECT_ID }}

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Firebase Functions
        working-directory: ./apps/functions
        run: npm run deploy
```

This is in the package.json script:

```
  "scripts": {
    "deploy": "firebase deploy --only functions --project=$PROJECT_ID"
  },
