### ISSUE TITLE
Error: An unexpected error has occurred.

### ISSUE THREAD

**Issue by mawaisnawaz** [w9jds/firebase-action#23]
Hello, I'm trying to deploy my code using Github's actions to firebase.

I am receiving this error
`Error: An unexpected error has occurred.
##[error]Docker run failed with exit code 2`

my code for deploy is as following

```
 deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:***
        env:
          FIREBASE_TOKEN: ${{ secrets.firebase_token }}
          PROJECT_ID: ***
```
