### ISSUE TITLE
Error Docker manifest v13.7.3

### ISSUE THREAD

**Issue by Zinoka** [w9jds/firebase-action#232]
Hello,

I have this error in my Github action now...

![Capture d'écran 2024-04-18 091401](https://github.com/w9jds/firebase-action/assets/44545827/6b304f7e-08f8-43b4-8798-4ad390943806)

Here, my .yml script

```
- name: Deploy to Firebase
  uses: w9jds/firebase-action@master
  with:
    args: deploy --only hosting:beta
```

same error with : 

```
- name: Deploy to Firebase
  uses: w9jds/firebase-action@v13.7.3
  with:
    args: deploy --only hosting:beta
```

I have changed the v13.7.3 by v13.7.2 to temporary fix it.
