### ISSUE TITLE
Flutter CLI not found

### ISSUE THREAD

**Issue by JaredEzz** [w9jds/firebase-action#248]
This action doesn't work for flutter web and exits with this error `Error: Flutter CLI not found, follow the instructions here https://docs.flutter.dev/get-started/install before trying again.`

It might be nice to have the flutter cli set up so we can use this action instead of installing the firebase cli to use `firebase deploy --only hosting` instead. But for anyone finding this, add this to your workflow instead for a workaround.

```yaml
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Enable Firebase webframeworks experiment
      run: firebase experiments:enable webframeworks

    - name: Deploy to Firebase
      env:
        PROJECT_ID: [insert your project id here]
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      run: |
        firebase deploy --only hosting
```
