### ISSUE TITLE
Using firebase-action to deploy python firebase functions.

### ISSUE THREAD

**Issue by oneranks** [w9jds/firebase-action#249]
Is `firebase-action` supports deploying py firebase functions? 

I can see everywhere only node is mentioned. I am trying to use this to deploy my py functions and stucked at below error:
```
Run w9jds/firebase-action@master
  with:
    args: deploy --only functions --project tinyefforts-beta
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.[1](https://github.com/Syncliner/tinyefforts-backend-fb/actions/runs/15509736794/job/43669097420#step:6:1)1.12/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.1[2](https://github.com/Syncliner/tinyefforts-backend-fb/actions/runs/15509736794/job/43669097420#step:6:2)/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/[3](https://github.com/Syncliner/tinyefforts-backend-fb/actions/runs/15509736794/job/43669097420#step:6:3).11.12/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.12/x6[4](https://github.com/Syncliner/tinyefforts-backend-fb/actions/runs/15509736794/job/43669097420#step:6:4)
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.12/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.12/x[6](https://github.com/Syncliner/tinyefforts-backend-fb/actions/runs/15509736794/job/43669097420#step:6:6)4/lib
    FIREBASE_TOKEN: ***
/usr/bin/docker run --name w9jdsfirebaseactionv1460_e0e362 --label 94ea1d --workdir /github/workspace --rm -e "pythonLocation" -e "PKG_CONFIG_PATH" -e "Python_ROOT_DIR" -e "Python2_ROOT_DIR" -e "Python3_ROOT_DIR" -e "LD_LIBRARY_PATH" -e "FIREBASE_TOKEN" -e "INPUT_ARGS" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/tinyefforts-backend-fb/tinyefforts-backend-fb":"/github/workspace" w[9](https://github.com/Syncliner/tinyefforts-backend-fb/actions/runs/15509736794/job/43669097420#step:6:9)jds/firebase-action:v14.6.0 deploy --only functions --project tinyefforts-beta
⚠  Authenticating with `FIREBASE_TOKEN` is deprecated and will be removed in a future major version of `firebase-tools`. Instead, use a service account key with `GOOGLE_APPLICATION_CREDENTIALS`: https://cloud.google.com/docs/authentication/getting-started

=== Deploying to 'tinyefforts-beta'...

i  deploying functions
i  functions: preparing codebase default for deployment
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
i  artifactregistry: ensuring required API artifactregistry.googleapis.com is enabled...
✔  functions: required API cloudfunctions.googleapis.com is enabled
✔  functions: required API cloudbuild.googleapis.com is enabled
✔  artifactregistry: required API artifactregistry.googleapis.com is enabled
i  functions: Loading and analyzing source code for codebase default to determine what to deploy

Error: Failed to find location of Firebase Functions SDK. Did you forget to run '. "/github/workspace/functions/venv/bin/activate" && python3.13 -m pip install -r requirements.txt'?
```

here is the pipeline yml:
```
name: Deploy to Firebase

on:
  push:
    branches:
      - maintest

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: beta
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          cd functions
          python -m venv venv
          source venv/bin/activate
          python311 -m pip install -r requirements.txt
          cd ..
      - name: Deploy to Firebase Beta Host
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions --project tinyefforts-beta
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
```

@w9jds , Hoping for your reply to get unblocked on above.

**Comment by w9jds** [comment]
In a previous step of your pipeline, use https://github.com/actions/setup-python this. That will setup python into your pipeline. If you want to farther improve your pipeline, use my other action https://github.com/w9jds/setup-firebase this will prevent it from setting up node and just your python that you care about. (while also allowing you to use multiple commands than just one).

**Comment by oneranks** [comment]
No luck for me! Still same issue: 
```
⚠  Authenticating with `FIREBASE_TOKEN` is deprecated and will be removed in a future major version of `firebase-tools`. Instead, use a service account key with `GOOGLE_APPLICATION_CREDENTIALS`: https://cloud.google.com/docs/authentication/getting-started
=== Deploying to 'tinyefforts-beta'...
i  deploying functions
i  functions: preparing codebase default for deployment
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
i  artifactregistry: ensuring required API artifactregistry.googleapis.com is enabled...
✔  functions: required API cloudfunctions.googleapis.com is enabled
✔  artifactregistry: required API artifactregistry.googleapis.com is enabled
✔  functions: required API cloudbuild.googleapis.com is enabled
i  functions: Loading and analyzing source code for codebase default to determine what to deploy
Error: Failed to find location of Firebase Functions SDK. Did you forget to run '. "/github/workspace/functions/venv/bin/activate" && python3.13 -m pip install -r requirements.txt'?
```


deploy file:
```
name: Deploy to Firebase

on:
  push:
    branches:
      - maintest

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: beta
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
          
      - name: Install dependencies
        run: |
          cd functions
          python3.13 -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          echo "Kshkhot: Checking py version"
          which python
          python --version
          echo "Kshkhot: Py version check completed"
          cd ..
          pip show firebase-functions | grep Version
      - name: Deploy to Firebase Beta Host
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions --project tinyefforts-beta
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
```

**Comment by gaieges** [comment]
I bumped into the same issue here, I presume the reason is because the environment vars that get set up by `source venv/bin/activate` is not making it's way into the container running the firebase command:

Config:
```yaml
  deploy_functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: python -m venv venv && source venv/bin/activate && python -m pip install -r requirements.txt
        working-directory: functions
      - name: deploy firebase functions
        uses: w9jds/firebase-action@v14.10.1
        with:
          args: deploy --only functions
        env:
          GCP_SA_KEY: ${{ secrets.SERVICE_ACCOUNT }}

```

Output:
```
Run w9jds/firebase-action@v14.10.1
  with:
    args: deploy --only functions
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.12.11/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.12.11/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.11/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.11/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.11/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.11/x64/lib
    GCP_SA_KEY: ***
/usr/bin/docker run --name w9jdsfirebaseactionv14101_1d0b99 --label cb647a --workdir /github/workspace --rm -e "pythonLocation" -e "PKG_CONFIG_PATH" -e "Python_ROOT_DIR" -e "Python2_ROOT_DIR" -e "Python3_ROOT_DIR" -e "LD_LIBRARY_PATH" -e "GCP_SA_KEY" -e "INPUT_ARGS" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/repo":"/github/workspace" w9jds/firebase-action:v14.10.1 deploy --only functions
Storing GCP_SA_KEY in /opt/gcp_key.json
Exporting GOOGLE_APPLICATION_CREDENTIALS=/opt/gcp_key.json

=== Deploying to 'myapp'...

i  deploying functions
i  functions: preparing codebase default for deployment
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
i  artifactregistry: ensuring required API artifactregistry.googleapis.com is enabled...
✔  functions: required API cloudfunctions.googleapis.com is enabled
✔  functions: required API cloudbuild.googleapis.com is enabled
✔  artifactregistry: required API artifactregistry.googleapis.com is enabled
i  functions: Loading and analyzing source code for codebase default to determine what to deploy

Error: Failed to find location of Firebase Functions SDK. Did you forget to run '. "/github/workspace/functions/venv/bin/activate" && python3.12 -m pip install -r requirements.txt'?
```

Note in the output there is no `PYTHONPATH` getting passed into the container.

I ended up going back to setting up node/firebase cli, adding credentials to the filesystem and doing the `venv/activate` to fix this for now:

```yaml

  deploy_functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14
      - name: install firebase tools
        run: npm install -g firebase-tools
      - run: python -m venv venv && source venv/bin/activate && python -m pip install -r requirements.txt
        working-directory: functions
      - run: echo '${{ secrets.SERVICE_ACCOUNT }}' > /tmp/firebase_service_account.json
      - name: deploy firebase functions
        run: firebase deploy --only functions
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/firebase_service_account.json

```
