### ISSUE TITLE
Deploy failed

### ISSUE THREAD

**Issue by Jbz797** [w9jds/firebase-action#28]
Since this morning I've been different errors when I deploy, sometimes `HTTP Error: 500, Internal error encountered` and sometimes `Failed to get status of functions deployments`.

The code : 

```
name: CI-Develop
on: [pull_request]

jobs:

  main:
    name: Lint, build and deploy
    runs-on: ubuntu-latest
    steps:

      - name: Node.js ⇒ Setup
        uses: actions/setup-node@master
        with:
          node-version: '10.x'
      - name: Git ⇒ Checkout project
        uses: actions/checkout@v1

      - name: Yarn ⇒ Get dependencies for back
        run: cd functions && yarn install
      - name: Lint ⇒ Lint back
        run: cd functions && npm run lint
      - name: Typescript ⇒ Build back
        run: cd functions && npm run build

      - name: Yarn ⇒ Get dependencies for front
        run: cd app && yarn install
      - name: Lint ⇒ Lint front
        run: cd app && npm run lint
      - name: React ⇒ Build front
        run: cd app && npm run build

      - name: Firebase ⇒ deploy
        uses: w9jds/firebase-action@master
        with:
          args: use staging && firebase deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
```
