### ISSUE TITLE
`deploy` command fails with `-m --message` argument

### ISSUE THREAD

**Issue by RoryDuncan** [w9jds/firebase-action#37]
I noticed I'm not able to add deploy messages with my deployments.
I tested `-m` vs `--message` as well as tested if my other parameters were a problem. It works as expected when I deploy manually.

### My action
``` yaml
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --message "CICD Deployment" --only hosting:production,hosting:cdn --project fuse-fonts
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          CI: true
```

It fails without an error message:
![image](https://user-images.githubusercontent.com/766828/80321983-755cf980-87d6-11ea-9ae8-3166a939a23e.png)

Reviewing the deploys in my firebase console shows that it was not deployed, so it isn't a case of a false-negative.

You can view my deployments, and their workflow files here: https://github.com/fuse-fonts/website/actions.

Upon removing the message it deploys successfully again.
