### ISSUE TITLE
Deploy to fire base step is failing.

### ISSUE THREAD

**Issue by Kuncheria-Kuruvilla** [w9jds/firebase-action#38]
Firebase deploy is failing with the following error 
Specified public directory 'build' does not exist, can't deploy hosting to site my-site.

[workflow.yml](https://github.com/Kuncheria-Kuruvilla/chainreaction.io/blob/master/.github/workflows/workflow.yml)

**Comment by mrsimpson** [comment]
you should configure the path to your build in your `firebase.json` so that the CLI can pick it up.
If you do not want hosting on GCP, you can also completely remove the hosting section.

**Comment by peterpeterparker** [comment]
same to me with `dist` which I've got it in my `firebase.json`.

```
{
  "hosting": {
    "public": "dist",
```

**Comment by peterpeterparker** [comment]
Found the solution. [actions/download-artifact](https://github.com/actions/download-artifact/releases) v2 was released three days ago. Don't know if it's a not documented breaking changes or a bug, anyway, it seems that form now on it downloads the artifacts on the root and not under a folder name as the one provided as `name`.

Therefore, to solve my issue, I had to provide the `path` attribute.

Was:

```
- name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
```

Is now solved with

```
- name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
```
