### ISSUE TITLE
GCP_SA_KEY format?

### ISSUE THREAD

**Issue by basickarl** [w9jds/firebase-action#39]
Can you give an example of the `GCP_SA_KEY` format. No matter what I do I can't get it working.

When I copy my GCP SA Key ID I get this error: `Error: Failed to authenticate, have you run firebase login?`

When I copy the whole JSON as a secret I get the following: `base64: invalid input`

```
            - name: GitHub Action for Firebase
              uses: w9jds/firebase-action@v1.3.0
              with:
                  args: deploy --only hosting
              env:
                  GCP_SA_KEY: ${{ secrets.GCP_SA_FIREBASE_CI_KEY }}
```
