### ISSUE TITLE
Error: Not in a Firebase app directory (could not locate firebase.json)

### ISSUE THREAD

**Issue by cilerler** [w9jds/firebase-action#4]
When I run the action, it says `Error: Not in a Firebase app directory (could not locate firebase.json)`

How can I set the path to look for project file?

```yaml
name: CI

on: 
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: GitHub Action for Firebase
      uses: w9jds/firebase-action@7d6b2b058813e1224cdd4db255b2f163ae4084d3
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      with:
        args: deploy

```

The **firebase.json** is in `\src` folder of the repo, and the folder with the content below.

```json
{
  "hosting": {
    "public": "public",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ]
  }
}
```

![image](https://user-images.githubusercontent.com/385958/63124524-7cf6ae00-bf79-11e9-8ae3-041fe36c2768.png)
