### ISSUE TITLE
Container action is only supported on Linux

### ISSUE THREAD

**Issue by FDiskas** [w9jds/firebase-action#41]
`runs-on: macos-latest`
```
 - name: Install Firebase
        uses: w9jds/firebase-action@master
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
```
