### ISSUE TITLE
Install java

### ISSUE THREAD

**Issue by Ridermansb** [w9jds/firebase-action#43]
Since some commands like `emulators:exec` [requires java][1].

I'm receiving 

>Error: firestore: Firestore Emulator has exited because java is not installed, you can install it from https://openjdk.java.net/install/

on Github Actions CI when on step...

```
      - name: Test
        uses: w9jds/firebase-action@v1.3.1
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          GCLOUD_PROJECT: ${{ secrets.nextGCLOUD_PROJECT }}
          PROJECT_ID: ${{ secrets.nextFIREBASE_PROJECTID }}
        with:
          args: emulators:exec --only functions,firestore \"npm run test --exit -- --forceExit --detectOpenHandles\"
```

[1]: https://github.com/firebase/firebase-tools/blob/de523a9cdf303444dc83700d3d816b90bc18a75b/src/emulator/downloadableEmulators.ts#L261
