### ISSUE TITLE
Action fails due to firebase CLI asking for user input

### ISSUE THREAD

**Issue by patrickk** [w9jds/firebase-action#44]
Was working great, then all the sudden on 06-05-2020 got this message and our deploys have been failing:

```i  firestore: there are 1 indexes defined in your project that are not present in your firestore indexes file. To delete them, run this command with the --force flag.
? Would you like to delete these indexes? Selecting no will continue the rest of
 the deployment. (y/N) 
```

This is how the .yml file is configured:

```
- name: Point to project and deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy --except functions
        env:
          # Better to use `secrets`, which we can set in GitHub settings rather than hard-coding token here
          FIREBASE_TOKEN: ${{ secrets.GH_ACTIONS_DEPLOY_TOKEN }}
          # Akin to `firebase use project_id_here`
          PROJECT_ID: "project_id_here"
          # Need to find firebase.json since it's not in root dir
          PROJECT_PATH: ./folder_name_here
```

Ran the deploy script locally, I get a similar warning but doesn't ask for user input, so deploy succeeds. 

I am using the latest action by the way

Maybe this is more of a scripting question, but would it be possible to ignore that user prompt and continue the rest of the script? Thank you.
