### ISSUE TITLE
Accessing output of previous job

### ISSUE THREAD

**Issue by bringel** [w9jds/firebase-action#5]
I'm having trouble accessing the output of a previous job using the following workflow config:

```
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build
  deploy:
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - name: deploy
        uses: w9jds/firebase-action@v1.0.1
        if: success()
        with:
          args: deploy --only hosting
        env:
          PROJECT_ID: vgbc-tracker
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_PROD }}
```

I thought that the `build` job should be putting its output in the `/github/workspace` directory and that should get picked up by this docker file.

Everything works great if I change my workflow to look like this:
```name: Master CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: deploy
        uses: w9jds/firebase-action@v1.0.1
        if: success()
        with:
          args: deploy --only hosting
        env:
          PROJECT_ID: vgbc-tracker
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_PROD }}
```
