### ISSUE TITLE
Cloud Function deployment failure

### ISSUE THREAD

**Issue by jperasmus** [w9jds/firebase-action#51]
Hi there,

Thanks for this very useful Github Action. We've been using it for quite some time and it has served us very well so far.

Today when we tried to deploy Cloud Functions the deployments started failing because the Node.js version clashed with the one set in our `package.json`. Since Cloud Functions only support Node.js v10, we have an `engine` entry in our `package.json` to restrict the Node.js version to v10. I see you've recently updated the Dockerfile for this action to use Node.js v12.18.1 which is the reason the error is occurring for us.

We've updated our workflow config to use `v1.3.1` of your action instead of `master` which was a bit reckless on our end.

Would it be possible for you to expose a property that we can use to set the Node.js version that your action should use or even better somehow automatically detect the Node.js version that our workflow is running with?

**Comment by w9jds** [comment]
I was actually looking at this myself last night. There were some issues with `firebase-tools` a few days back that was causing issues with the `node:10-slim` image and bumping to a more recent version fixed it. I was planning on bumping it back down, but the branch isn't ready for general use yet as I'm still seeing issues with the `npm install -g firebase-tools` command on it. I also thought about allowing you to supply a version, but I haven't tested to to see if docker would support it unless I pulled a full OS image and installed node manually.

**Comment by w9jds** [comment]
@jperasmus can you point your action to `@feature/jdk` and let me know if that works. It should use node version `v10.21.0`. I can not actually let you choose the node version until GitHub builds the ability for us to pass `build-args` which has been asked for in the feedback sections.

**Comment by jperasmus** [comment]
Thanks for the quick feedback.

I'm looking at the `actions.yaml` options and in particular the optional [`inputs`](https://help.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs). Don't you think there is a way to use the `inputs` to pass an env var through to the Dockerfile. I have no idea whether it is possible, just throwing around some ideas.

In the `actions.yaml` add the `inputs`:

```yaml
inputs:
  nodeVersion:
    description: 'Node.js version to use'
    required: false
    default: 'latest'
```

In the user's workflow file they can then pass the optional `nodeVersion` through as a [`with`](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepswith) argument:

```yaml
- name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          nodeVersion: 'v10.21.0'
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
```

Also in the `actions.yaml` file we can set the Node.js version env var in the [`runs`](https://help.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsenv) section:

```yaml
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    CUSTOM_NODE_VERSION: ${{ inputs.nodeVersion }}
```

The docs says that these env vars are set in the container environment, so should hopefully then be available in the `Dockerfile` to use.

Like I mentioned, I have no idea if this would work, but an idea. What do you think?

**Comment by w9jds** [comment]
Inputs and Environment variables are only set for run of the docker images, not on build. I already built this stuff into a side branch, but it won't work until GitHub adds the ability to add docker `build-args`

**Comment by jperasmus** [comment]
Gotcha! Only runtime env vars. 👍 

Another option might be to have different `Dockerfile`s for a few different versions of Node.js and then in the `actions.yaml` have something like this:

```yaml
runs:
  using: 'docker'
  image: 'Dockerfile${{ inputs.nodeVersion }}'
```

That could resolve to a `Dockerfile10` for instance.

Anyhows, just trying to think off workarounds while we wait for GitHub to add support for `--build-args`. For our use case, we explicitly set the action to `uses: w9jds/firebase-action@v1.3.1` which is working fine. I'll try the `w9jds/firebase-action@feature/jdk`, but I'm hesitant to use one pointing to a branch again that might be changed or removed in the future.
