### ISSUE TITLE
Error: An action could not be found

### ISSUE THREAD

**Issue by Lukewh** [w9jds/firebase-action#56]
```
##[error]An action could not be found at the URI 'https://api.github.com/repos/w9jds/firebase-actions/tarball/v1.5.0'
```

Using:
```
- name: Deploy function to Firebase
  uses: w9jds/firebase-action@v1.5.0
  with:
    args: deploy --only functions
  env:
    FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
```

Get the same with `w9jds/firebase-action@master` too.
