### ISSUE TITLE
eslint inside functions directory and deploy with host assets

### ISSUE THREAD

**Issue by joeleduardo** [w9jds/firebase-action#58]
Sorry if i reopen this issue..... i have in **functions/package.json** the **eslint .** command, so how can i solve this error without delete the configuration ?

```
i  deploying functions, hosting
Running command: npm --prefix "$RESOURCE_DIR" run lint

> functions@ lint /github/workspace/functions
> eslint .

sh: eslint: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! functions@ lint: `eslint .`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the functions@ lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /github/home/.npm/_logs/2020-09-03T12_50_56_138Z-debug.log

Error: functions predeploy error: Command terminated with non-zero exit code1
```

**Comment by joeleduardo** [comment]
OK so i change my approach but i cant deploy just the hosting:

```
=== Deploying to '***'...

i  deploying hosting
i  hosting[***]: beginning deploy...
i  hosting[***]: found 254 files in public
i  hosting: adding files to version [0/254] (0%). //------> HERE <---------
✔  hosting[***]: file upload complete
i  hosting[***]: finalizing version...
✔  hosting[***]: version finalized
i  hosting[***]: releasing new version...
✔  hosting[***]: release complete

✔  Deploy complete!

Project Console: https://console.firebase.google.com/project/***/overview
Hosting URL: https://***.web.app
```
Basically is deploying nothing here my config file:

```
name: Build and deploy landing page to staging
on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'functions/**'

jobs:
  build:
    name: Build landing page
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: public
          path: public/**
  deploy:
    name: Deploy landing page
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: public
          path: public/**
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.GATSBY_FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.GATSBY_FIREBASE_PROJECT_ID }}
```
