### ISSUE TITLE
Either FIREBASE_TOKEN or GCP_SA_KEY is required to run commands with the firebase cli

### ISSUE THREAD

**Issue by arthurkok2** [w9jds/firebase-action#60]
When my "Deploy to Firebase" step runs, I get the error:

`Either FIREBASE_TOKEN or GCP_SA_KEY is required to run commands with the firebase cli`

This is what the step looks like in my yaml file
```
    - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
```

and I have my secret correctly set as well:

![image](https://user-images.githubusercontent.com/5326296/94615606-08162e80-0276-11eb-82fb-9535e51bdcf3.png)

What could be the issue?
Thanks
