### ISSUE TITLE
Error: firebase use must be run from a Firebase project directory

### ISSUE THREAD

**Issue by sha-one** [w9jds/firebase-action#61]
I keep running into this error with a workflow I'm trying to setup. 

I can confirm firebase.json is indeed in the main repo directory. And the same repo runs firebase commands (ie firebase use) locally with no issues.

I'm new to Github Actions, so may have missed something?!

This is the debug log from the last Github Action

```
/usr/bin/docker run --name e5c35409207c72d03464f95ff6469bda12cf7_d1057e --label 1e5c35 --workdir /github/workspace --rm -e PROJECT_ID -e BUCKET -e FIREBASE_TOKEN -e CLOUDSDK_METRICS_ENVIRONMENT -e GCLOUD_PROJECT -e GOOGLE_APPLICATION_CREDENTIALS -e INPUT_ARGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_DEBUG -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/my-app-v2/my-app-v2":"/github/workspace" 1e5c35:409207c72d03464f95ff6469bda12cf7 auth:export ./auth.json
```
```
setting firebase project to my-app

Error: firebase use must be run from a Firebase project directory.

Run firebase init to start a project directory in the current folder.
```

**Comment by w9jds** [comment]
Need more information. The debug info doesn't show much except that you aren't running the action from inside of your project directory. What does your action flow look like?

It looks like your pipeline isn't setup properly. You need to actually build your project and pull it into the job steps to use it as the example in the README shows.

**Comment by sha-one** [comment]
Thanks @w9jds 

This is my workflow:

Everything works fine, all the npm install and build steps up until it gets to  
_- name: Firebase GitHub Action, Backup auth_

Where I get the error from my initial comment above.

```
name: Backup Firestore Auth

#on:
#  schedule:
#    - cron:  '*/3 * * * *'
on: [workflow_dispatch]

env:
  PROJECT_ID: myapp
  BUCKET: 'gs://myapp.appspot.com'
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  
jobs:
  build:

    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
  backup-auth:
    runs-on: ubuntu-latest
    steps:

    - name: Set date output
      id: get-date
      run: |
        echo ::set-output name=date::$(/bin/date -u "+%a-%d-%b-%Y--%H-%M-%S")
    - name: Gcloud GitHub Action
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Firebase GitHub Action, Backup auth
      uses: w9jds/firebase-action@master
      env:
        PROJECT_ID: $PROJECT_ID
        FIREBASE_TOKEN: $FIREBASE_TOKEN
      with:
        args: auth:export auth.json

    - name: Save auth to Bucket
      run: | 
        gsutil cp auth.json $BUCKET/livebackups/auth/${{ steps.get-date.outputs.date }}
```

**Comment by w9jds** [comment]
Apologies for the delay!

Yea, you store your build as an artifact, but you don't repull it, so your second step doesn't actually have your project in it, so for all intensive purposes you aren't in a firebase directory.

**Comment by sha-one** [comment]
Thanks @w9jds that little bit of vital-info helped get things working :)
This is what I ended up with, for backing up firebase auth:

```
name: Backup Firestore Auth

on:
  schedule:
    - cron:  '0 0 * * *'

env:
  BUCKET: 'gs://myapp.appspot.com'
  
jobs:
  backup-auth:
    name: Backup-auth
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Set date output
        id: get-date
        run: |
          echo ::set-output name=date::$(/bin/date -u "+%a-%d-%b-%Y--%H-%M-%S")
      - name: Gcloud GitHub Action
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Firebase GitHub Action, Backup auth
        uses: w9jds/firebase-action@master
        env:
          PROJECT_ID: production
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        with:
          args: auth:export ./auth.json

      - name: Save auth to Bucket
        run: | 
          gsutil cp ./auth.json $BUCKET/livebackups/auth/${{ steps.get-date.outputs.date }}
```
