### ISSUE TITLE
How to set working directory for the action?

### ISSUE THREAD

**Issue by melchoir55** [w9jds/firebase-action#63]
We run our tests inside a docker container. This ensures that the same thing happening on our development machines occurs in ci. When done with our tests, we want to do a deployment. I have included the action script below:

```
name: dev-push-ci

on:
  push:
    branches: [ dev ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t fbtest .
      - name: Run tests
        run: docker run fbtest /bin/sh /src/test/run_ci_tests.sh
        command docker exec -it <container name> /bin/bash
      - name: Retrieve build artifacts
        run: docker cp $(docker create --rm fbtest:latest):/src/. ./dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only storage,firestore,functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: likemindedly-stage
          PROJECT_PATH: dist
```

You will notice we are extracting the entire project directory from the docker container using `docker cp` and dropping it in the working directory in a folder called `dist`. Now, `dist` contains the build project including dependencies. These are required for the github action. We tried using `PROJECT_PATH` but it looks like that just tells the action to use the `json` file in the path rather than actually designating the path to the project.

How can we set our working directory such that the action will run inside our `dist` folder...?

**Comment by w9jds** [comment]
Github Actions are built on docker, unless you are deploying a docker image, building a new one to run tests doesn't make much sense. If you absolutely want to do this you should point a step to the `dockerfile` so that it runs the tests like it would a step in the action, Each step does it's own thing and is kind of independent of the other. Firebase Action is it's own docker image in it's own right. How you do this should probably be `Build step` => `Test step` => `Deploy Step` and the build stores to an artifact and pulls in each step.

**Comment by melchoir55** [comment]
Unless the github action is going to use our Dockerfile then it makes sense for us to build it. The file has a bunch of instructions which prepare the various dependencies and such used by the tests, including bringing up the emulators.
We tried uploading that `dist` directory in the above code sample as an artifact, but it took 45 minutes to upload, which seemed insane.

**Comment by w9jds** [comment]
Yes, the `use` argument for a step can point to a project's `dockerfile` which will run and you pass in an argument. It will take a bit of modification but will work better. However, you are still thinking that they are all connected, they aren't. Each step is independent of each other (but can require the previous to pass). Test will run it's docker, then you have a new step for deploy, you pull your artifact from your build, and then use the deployment. 

```  
build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Setup Node.js v12.18.4
        uses: actions/setup-node@master
        with:
          node-version: 12.18.4
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build-prod
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
  test:
    name: Test
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t fbtest .
      - name: Run tests
        run: docker run fbtest /bin/sh /src/test/run_ci_tests.sh
        command docker exec -it <container name> /bin/bash

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:prod
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
```

If your build and test aren't independent they should be, or it wouldn't be a proper CI step system and brakes the whole aspect of the steps.
