### ISSUE TITLE
Cannot find project when using PROJECT_ID

### ISSUE THREAD

**Issue by bvelasquez** [w9jds/firebase-action#74]
Error: Invalid project selection, please verify project staging exists and you have access.

The Project ID exists, and shows up when I run firebase projects:list. Logged in with the same account used to retrieve the FIREBASE_TOKEN.

I do have a .firebaserc file. Could this be interfering?

Deploy section:

```
deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: myprojectid
```
