### ISSUE TITLE
can't upload Cloud Functions, no node_modules

### ISSUE THREAD

**Issue by bartekpacia** [w9jds/firebase-action#77]
I have the following workflow file, which I want to build my Cloud Functions (written in TypeScript, source residing in `functions/src`, transpiled to JavaScript residing in `functions/lib`):
```
name: Deploy to Cloud Functions

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci --arch=x64 --platform=linuxmusl
        working-directory: ./functions
      - name: Build
        run: npm run build
        working-directory: ./functions
      - name: Lint
        run: npm run lint
        working-directory: ./functions
      - name: Archive compiled source
        uses: actions/upload-artifact@v2
        with:
          name: lib
          path: ./functions/lib

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Download compiled source
        uses: actions/download-artifact@master
        with:
          name: lib
          path: ./functions/lib
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
```

it fails on **deploy to Firebase** step, logs below:

```
=== Deploying to 'discoverrudy'...

i  deploying functions
Running command: npm --prefix "$RESOURCE_DIR" run build

> functions@ build /github/workspace/functions
> tsc

sh: tsc: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! functions@ build: `tsc`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the functions@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /github/home/.npm/_logs/2020-12-24T05_01_52_610Z-debug.log

Error: functions predeploy error: Command terminated with non-zero exit code1
```

I tried to upload the `node_modules` folder in `build` job and then download it in `deploy` job, but it's waaay to heavy. 
How can I successfully upload?

PS I also think that README should be updated with instructions on how to deploy Cloud Functions, not only Hosting.

Thanks in advance!

**Comment by phongyewtong** [comment]
have this same issue too. have you figure it out?

**Comment by bartekpacia** [comment]
unfortunately no
I kinda solved by having a single job named `build_deploy` which, well, builds and deploys to Cloud Functions.

**Comment by riker09** [comment]
You should run `npm ci` or `npm install --only=prod` (or set `NODE_ENV` to `production` beforehand) right *before* deploying. Firebase functions are based on NodeJS and need a `node_modules` folder.

You can copy from your build job by using artiifacts. However, building requires dev-dependencies, which can be quite heavy (filesize-wise).

Here's my (examplary) build & deploy workflow file:

```yaml
name: Build and Deploy Functions
on:
  push:
    branches:
    - main
    - develop
    - release/*
    paths:
    - '.github/workflows/deploy-firebase-functions.yaml' ## This file
    - 'functions/**'

env:
  RESOURCE_DIR: functions

jobs:
  build:
    name: Build Firebase Functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci --no-audit
        working-directory: ${{ env.RESOURCE_DIR }}

      - name: Build
        run: npm run build
        working-directory: ${{ env.RESOURCE_DIR }}

      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: lib
          path: ${{ env.RESOURCE_DIR }}/lib

  deploy:
    name: Deploy Firebase Functions
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci --no-audit --only=prod
        working-directory: ${{ env.RESOURCE_DIR }}

      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: lib
          path: ${{ env.RESOURCE_DIR }}/lib

      - name: Prepare deploy
        run: |
          branch="${GITHUB_REF/"refs/heads/"/}"
          case "${branch%%/*}" in \
            main|master) project_id="PROJECT_ID_PRODUCTION ;; \
            release)     project_id="PROJECT_ID_STAGING" ;; \
            develop)     project_id="PROJECT_ID_TESTING ;; \
          esac;
          echo "PROJECT_ID=$project_id" >> $GITHUB_ENV

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions --force
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ env.PROJECT_ID }}
```
