### ISSUE TITLE
Error parsing triggers: Cannot find module 'firebase-functions'

### ISSUE THREAD

**Issue by phongyewtong** [w9jds/firebase-action#78]
It cannot find the firebase-functions module.

if there is an example of how to deploy firebase function will be great.

```
name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Functions 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Firebase Dependencies
        run: npm install
      - name: Install Function Dependencies
        run: cd functions && npm install
      - name: Build
        run: cd functions && npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: lib
          path: functions/lib
  deploy:
    name: Deploy Functions to Dev
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: lib
          path: functions/lib
      - name: Use Firebase Dev Project
        uses: w9jds/firebase-action@master
        with:
          args: use dev
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy to Firebase Dev
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
```

```
/usr/bin/docker run --name w9jdsfirebaseactionlatest_69f708 --label cc4956 --workdir /github/workspace --rm -e FIREBASE_TOKEN -e INPUT_ARGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/tws-functions-v2/tws-functions-v2":"/github/workspace" w9jds/firebase-action:latest deploy --only functions

=== Deploying to 'dev-tws'...

i  deploying functions
✔  functions: Finished running predeploy script.
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
✔  functions: required API cloudbuild.googleapis.com is enabled
✔  functions: required API cloudfunctions.googleapis.com is enabled
i  functions: preparing functions directory for uploading...

Error: Error parsing triggers: Cannot find module 'firebase-functions'
Require stack:
- /github/workspace/functions/lib/firebase/index.js
- /github/workspace/functions/lib/index.js
- /usr/local/lib/node_modules/firebase-tools/lib/triggerParser.js

Try running "npm install" in your functions directory before deploying.
```
