### ISSUE TITLE
Using FIREBASE_TOKEN it fails saying that it can not find firebase.json

### ISSUE THREAD

**Issue by danielgomezrico** [w9jds/firebase-action#84]
I get this error:
> Error: Not in a Firebase app directory (could not locate firebase.json)

My setup:
```YAML
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        PROJECT_PATH: build/web/
```

I want to use `FIREBASE_TOKEN` and not the `.json`, what should I do?

**Comment by gauravgupta98** [comment]
I am also facing a similar issue. 
My setup -
```
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - run: npm ci
      - run: CI=false npm run build
      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@v1.5.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
```
I want to run job on client directory in my repo and have setup default working directory for the job but the job is failing with below error. Please help.
```
Error: Not in a Firebase app directory (could not locate firebase.json)
```
