### ISSUE TITLE
How to copy data to the action / Misses cypress binary

### ISSUE THREAD

**Issue by sceee** [w9jds/firebase-action#90]
I want to execute E2E tests in scope of the Firebase emulators.

Therefore, in my Github Actions `yml`, I define the following test step:
```
... (Install dependencies etc. using npm ci...)
    - name: Test
      uses: w9jds/firebase-action@v2.0.0
      with:
        args: emulators:exec --import=./test/emulatordata --debug \"npm run test:emulators:clientapp:execute\"
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_CI_TOKEN }}
        PROJECT_PATH: backend/functions
```

So, what I'm trying to do is:
1. Execute the emulator's using `firebase emulators:exec`
2. have it import the test data and
3. while emulators are running, execute the tests for the client app (another project - the Frontend -> `npm run test:emulators:clientapp:execute` does that).

Now here comes the issue:
`npm run test:emulators:clientapp:execute` contains unit as well as E2E tests using Cypress.
Unit tests work but Cypress tests fail because the Cypress binary is missing:
```
The cypress npm package is installed, but the Cypress binary is missing.

We expected the binary to be installed here: /github/home/.cache/Cypress/6.8.0/Cypress/Cypress

Reasons it may be missing:

- You're caching 'node_modules' but are not caching this path: /github/home/.cache/Cypress
- You ran 'npm install' at an earlier build step but did not persist: /github/home/.cache/Cypress

Properly caching the binary will fix this error and avoid downloading and unzipping Cypress.

Alternatively, you can run 'cypress install' to download the binary again.

https://on.cypress.io/not-installed-ci-error
```

I guess it's because the working directory gets mapped to the container executed by the `w9jds/firebase-action` step but `/github/home/.cache` or other directories do not.

I thought I now have several possibilities:
* Execute `cypress install` "within" the `w9jds/firebase-action` but there is no possibility as far as I know to execute other commands prior to the firebase command that gets executed
* Somehow copy the `/github/home/.cache` directory from the "host" (Github Actions native VM) to the `w9jds/firebase-action` container - but there is no way I know I could copy or map directories (like the docker `-v` parameter)

Is there any way I could get the cypress binary in the `w9jds/firebase-action` container or is there any other solution?

I guess, by using plain `npm i -g firebase-tools` in the "host" (and not using `w9jds/firebase-action` at all), I could also just start the emulators in the background using something like this:
```
firebase emulators:start &
npm run test:emulators:clientapp:execute
```
but this would somehow be dirty as I would have to wait until the emulators start up and also would have no auto cleanup/close after the script ended. So all the cuteness of `firebase emulators:exec` would be gone and therefore, I would like to stick to `w9jds/firebase-action`.

Does anyone have a solution idea for this problem?
